Give the admin rights to fuseml-core ServiceAccount
fuseml/fuseml pull request #108
Opened 2021-05-26 08:20 UTC by jsuchome

This is fuseml-core can delete various resources forming FuseML
applications (secrets, serviceaccounts, inferenceservices etc.)

Closes #107

2021-05-31 19:18 UTC, stefannica requested changes
I haven't looked at using the `cluster-admin` cluster role, because I wanted to try using regular roles first. I tried this modified `fuseml-core-tekton` role on my local cluster and it worked (i.e. the fuseml core service could successfully delete all resources from the application):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fuseml-core-tekton
  namespace: fuseml-workloads
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - create
  - get
  - list
  - delete
```

Could you please try this instead and tell me if it works ? If yes, I think you could also rename the role, rolebinding and even serviceaccount from `fuseml-core-tekton` to `fuseml-core` to be consistent with the wider permissions.

2021-06-01 06:05 UTC, jsuchome commented
That is not "regular role". You literally created a role with admin privileges, i.e. cluster role.

I agree with renaming though.

2021-06-01 08:28 UTC, stefannica commented
@jsuchome you're perfectly right, the default `cluster-admin` cluster role has exactly the same permissions. I also looked at the `admin` cluster role, which is an aggregate of various roles installed by various tools. I couldn't find anything related to KFServing CRDs in there, which means it's not enough to allow you to delete KFServing inference services. I suspect our KFServing installation does not extend the `admin` cluster role as it should.

Let's stick to your role then. Thanks for educating me.

2021-06-01 08:33 UTC, stefannica approved these changes
The rename would still be nice, but it's up to you.

2021-06-01 09:42 UTC, jsuchome commented
I've renamed the serviceaccount to `fuseml-core`

 ... now it seems that since it has a cluster-role assigned, we do not need `fuseml-core-tekton` role and `fuseml-core-tekton-binding` rolebinding any more so I could delete it ... or maybe there is some scenario where we could have use for both roles, tekton specific one and the admin one?

2021-06-01 10:03 UTC, stefannica commented
> I've renamed the serviceaccount to `fuseml-core`
> 
> ... now it seems that since it has a cluster-role assigned, we do not need `fuseml-core-tekton` role and `fuseml-core-tekton-binding` rolebinding any more so I could delete it ... or maybe there is some scenario where we could have use for both roles, tekton specific one and the admin one?

I agree, they can be deleted. Let's keep it as simple as possible :)

2021-06-01 12:18 UTC, stefannica approved these changes
Great, thank you !

2021-06-01 13:21 UTC, merged