ci: Run tests before release
fuseml/fuseml pull request #302
Opened 2021-11-25 16:55 UTC by flaviodsr

Include test jobs, the same that are executed by the CI, as part of
the release workflow.

2021-11-26 11:38 UTC, jsuchome commented on .github/workflows/release.yml
> +    uses: flaviodsr/fuseml/.github/workflows/ci.yml@main
this should point to main repo

2021-11-26 12:51 UTC, jsuchome commented on .github/workflows/release.yml
> +    uses: flaviodsr/fuseml/.github/workflows/get-fuseml-installer.yml@main
Same here

2021-11-29 09:22 UTC, jsuchome requested changes
see comments

2021-11-29 14:22 UTC, stefannica commented on .github/workflows/release.yml
> +    uses: flaviodsr/fuseml/.github/workflows/ci.yml@main
fixed

2021-11-29 14:22 UTC, stefannica commented on .github/workflows/release.yml
> +    uses: flaviodsr/fuseml/.github/workflows/get-fuseml-installer.yml@main
fixed

2021-11-29 14:29 UTC, stefannica approved these changes

2021-11-29 15:00 UTC, jsuchome approved these changes

2021-11-29 22:26 UTC, merged